(define (subsets s)
  (if (null? s)
      (list '())
      (let ((rest (subsets (cdr s))))
        (append rest (map (lambda (x) (cons (car s) x)) rest)))))

(define (main-ex-2-32)
  (define S (list 1 2 3))
  (display (subsets S))
  (newline))
